version: "3.9"

services:
  # ------------------------------
  # 1. REVERSE PROXY
  # ------------------------------
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    networks:
      - public
      - internal

  # ------------------------------
  # 2. BASE DE DATOS (NO EXPUESTA)
  # ------------------------------
  postgres:
    image: postgres:17
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-backups:/backups
    networks:
      - internal

  # ------------------------------
  # 3. BACKEND (NODE)
  # ------------------------------
  backend:
    build: ./backend
    restart: always
    container_name: backend
    environment:
      PORT: 5020
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      WEB_CORS: ${WEB_CORS}
      JWT_SECRET: ${JWT_SECRET}
      API_CONTIFICO: ${API_CONTIFICO}
      API_KEY: ${API_KEY}
      API_TOKEN: ${API_TOKEN}
      DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - internal          # para comunicarse con DB y otros servicios internos
      - public-internet   # para poder salir a Internet
    depends_on:
      - postgres
    dns:
      - 8.8.8.8
      - 1.1.1.1

  # ------------------------------
  # 4. FRONTEND (VITE, SERVIDO POR NGINX)
  # ------------------------------
  frontend:
    build: ./frontend
    restart: always
    container_name: frontend
    networks:
      - internal
    depends_on:
      - backend

  landingpage:
    build: ./landingpage
    container_name: landingpage
    restart: always
    networks:
      - internal

# ------------------------------
# VOLUMES
# ------------------------------
volumes:
  npm-data:
  npm-letsencrypt:
  postgres-data:

# ------------------------------
# NETWORKS
# ------------------------------
networks:
  public:
  internal:
    internal: true      # base de datos y servicios internos siguen aislados
  public-internet:
    driver: bridge       # backend puede salir a Internet